#!/usr/bin/with-contenv sh

# make our folders
mkdir -p \
	/config/www/uploadx

# install uploadx
if [ ! -e "/config/www/uploadx/index.php" ]; then
	curl -L https://github.com/UploadX/UploadX/archive/master.tar.gz | tar -xzvC /config/www/uploadx --strip-components 1
fi

if [ ! -e "/config/www/uploadx/lib/config.php" ]; then
	cp /defaults/config.php /config/www/uploadx/lib/config.php
fi

# Setup Nginx
if [ ! -e "/config/nginx/snippets/apps/uploadx.conf" ]; then
	mkdir -p /config/nginx/snippets/apps
	cp /defaults/uploadx.conf /config/nginx/snippets/apps/uploadx.conf
fi

if [ ! -e "/config/nginx/snippets/php/7.0.conf" ]; then
	mkdir -p /config/nginx/snippets/php
	cp /defaults/7.0.conf /config/nginx/snippets/php/7.0.conf
fi

# Setup Domain
if [ ! -z "$DOMAIN" ]; then
	sed -i -e "s/server_name _;/server_name $DOMAIN;/g" /config/nginx/site-confs/default
	sed -i -e "s/https:\/\/enter.your.site.here.com\/$DOMAIN/g" /config/www/uploadx/lib/config.php
fi
# permissions
chown -R abc:abc \
	/config /data
